# Generated by Django 5.1.6 on 2025-02-15 11:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='demand_multipier',
            new_name='demand_multiplier',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='traffic_multipier',
            new_name='traffic_multiplier',
        ),
        migrations.AlterField(
            model_name='ride',
            name='demand_level',
            field=models.CharField(choices=[('normal', Decimal('1.0')), ('peak', Decimal('1.8'))], max_length=10),
        ),
        migrations.AlterField(
            model_name='ride',
            name='traffic_level',
            field=models.CharField(choices=[('low', Decimal('1.0')), ('normal', Decimal('1.2')), ('high', Decimal('1.5'))], max_length=10),
        ),
    ]
