# Generated by Django 5.1.6 on 2025-02-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_rename_demand_multipier_ride_demand_multiplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='rider',
        ),
    ]
